# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [8]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(5)
arr_2 = np.arange(1,10,2)

In [9]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([0, 1, 2, 3, 4, 1, 3, 5, 7, 9])

In [14]:
# Vertical stacking - Increasing the number of row


# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1,arr_2))

In [15]:
# Checking the dimensions of the array
arr_3.ndim

2

In [16]:
# Printing the created array
arr_3

array([[0, 1, 2, 3, 4],
       [1, 3, 5, 7, 9]])

In [17]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

In [19]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(1,11)

# Printing the created array
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = arr_4.reshape(5,2)

In [21]:
# Checking the rows and columns in the created array
arr_5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [25]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape(5,4)

# Checking the rows and columns in the created array
arr_5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [26]:
# Stacking arr_5 and arr_6
np.hstack((arr_5, arr_6))

array([[ 1,  2, 20, 21, 22, 23],
       [ 3,  4, 24, 25, 26, 27],
       [ 5,  6, 28, 29, 30, 31],
       [ 7,  8, 32, 33, 34, 35],
       [ 9, 10, 36, 37, 38, 39]])

In [27]:
# Check the structure of arr_6
arr_6.shape

(5, 4)