In [1]:
import numpy as np

In [4]:
my_list = np.array([[11, 12, 13, 14],
 [21, 22, 23, 24],
 [31, 32, 33, 34]])

In [6]:
cf = my_list[:,0]
cf

array([11, 21, 31])

In [8]:
rf = my_list[0,:]
rf

array([11, 12, 13, 14])

In [9]:
cl = my_list[:,-1]
cl

array([14, 24, 34])

In [10]:
print(cl)

[14 24 34]
